# Generated by Django 3.1.5 on 2021-06-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='Lastname',
        ),
    ]
