# Generated by Django 3.1.5 on 2021-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210601_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='gmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='last',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='naam',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
